/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Banner: typeof import('./src/components/layout/Banner.vue')['default']
    CartModal: typeof import('./src/components/cart/CartModal.vue')['default']
    Footer: typeof import('./src/components/layout/Footer.vue')['default']
    Header: typeof import('./src/components/layout/Header.vue')['default']
    ProductCard: typeof import('./src/components/products/ProductCard.vue')['default']
    ProductGrid: typeof import('./src/components/products/ProductGrid.vue')['default']
    ProductsCategories: typeof import('./src/components/products/ProductsCategories.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
